# Site settings
title: Lars Lysel
email: webmaster@lysel.net
description: "Lars Lysel"
baseurl: "https://lars.lysel.net"
#url: http://lars.lysel.net

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
highlighter: rouge
paginate: 15
#exclude: ["node_modules"]

gems:
  - jekyll-sitemap



